# -*- coding: utf-8 -*-
"""Web_Scrape.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e-Wmo5UkValby5E30cmEHhf-AXfdWXjA
"""

pip install beautifulsoup4

pip install lxml

pip install requests

from bs4 import BeautifulSoup
import requests
from pandas import DataFrame
location=[]
PubCont=[]
Count=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
source=requests.get('https://www.journals.elsevier.com/journal-of-hydrology/editorial-board').text
soup=BeautifulSoup(source, 'lxml')
i=0
match= soup.find('div', class_='off-canvas-wrap')
large=match.div.main
content=large.find('div', class_='row no-padding')
column=content.find('div', class_='content large-8 medium-8 small-12 columns').div
editors=column.find('div', class_='publication-editors')
for final in editors.find_all('div', class_='publication-editor'):
  location.append(final.span.text)
  SAR=location[i].split(',')
  if((SAR[-2].lstrip()).lower()=='hong kong' and (SAR[-1].lstrip()).lower()=='china'):
    PubCont.append(SAR[-2].lstrip().lower())
  else:
    PubCont.append(SAR[-1].lstrip().lower())
  i+=1
  
print(PubCont)

CountryList=['usa','united states of america','united kingdom','uk','china','india','russia','france','germany','japan','spain','switzerland','australia','canada','italy','hong kong','singapore']
for Countries in PubCont:
  if(Countries == CountryList[0] or Countries == CountryList[1]):
    Count[0]+=1
  elif(Countries == CountryList[2] or Countries == CountryList[3]):
    Count[1]+=1
  elif(Countries == CountryList[4]):
    Count[2]+=1
  elif(Countries == CountryList[5]):
    Count[3]+=1
  elif(Countries == CountryList[6]):
    Count[4]+=1
  elif(Countries == CountryList[7]):
    Count[5]+=1
  elif(Countries == CountryList[8]):
    Count[6]+=1
  elif(Countries == CountryList[9]):
    Count[7]+=1
  elif(Countries == CountryList[10]):
    Count[8]+=1
  elif(Countries == CountryList[11]):
    Count[9]+=1
  elif(Countries == CountryList[12]):
    Count[10]+=1
  elif(Countries == CountryList[13]):
    Count[11]+=1
  elif(Countries == CountryList[14]):
    Count[12]+=1
  elif(Countries == CountryList[15]):
    Count[13]+=1
  elif(Countries == CountryList[16]):
    Count[14]+=1
  else:
    Count[15]+=1
print(Count)
df=DataFrame(Count)
export=df.to_excel (r'G:\Work\KC Wong\Test.xlsx', index = None, header=True)
print(df)

